### PR TITLE
fix: updates workflow for v9 of semantic release

### LINKED ISSUE #37: The semantic release job is not updating the repository
## Describe the bug

Not an application bug, but a bug in the CI workflow that needs to be resolved. The semantic release job ran with no output and still passed. Not commit, tags, release were created.

## To Reproduce

1. Merge changes to main
1. Observe the that the job passes with no output

## Expected behavior

Release to be created

## Screenshots / Logs.

Associated job with issue - https://github.com/oscal-compass/compliance-trestle-fedramp/actions/runs/8633856602/job/23709506722

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

### PR DESCRIPTION
**Pull request by jpower432**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] All commits are signed-off.

## Summary

Updates semantic release logic to match `trestle`

Fixes #37

Related to https://github.com/oscal-compass/compliance-trestle/pull/1564 and will require the same `pypi` setup

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle-fedramp)

### CODE REVIEW

**Review by vikas-agarwal76 — APPROVED** [review]
LGTM

**Comment by jpower432** [comment]
@vikas-agarwal76 Thanks for the review. I did a additional pre-merge review and realized that the `MINOR` variable was not being set in the release workflow. Added https://github.com/oscal-compass/compliance-trestle-fedramp/pull/38/commits/a7ff1eea295a4609039fe53bbdf0911e26d802bc so we can set the value from the repository variables.

**Comment by jpower432** [comment]
Currently working on debugging this CI [failure](https://github.com/oscal-compass/compliance-trestle-fedramp/actions/runs/8836037883/job/24261835344). This issue may be related to https://bugs.python.org/issue44061 and the solution may be to pin to another version of python 3.8 and add an issue to `compliance-trestle`.

**Comment by jpower432** [comment]
Closing in favor of #46

**Pull request closed without merging**
